#+TITLE: Mosè Giordano
#+HTML_LINK_HOME:

Here is a list of some of my activities.  Some sections are in Italian, others
in English.  Sorry about the mess.

*Fisica e matematica*
- Miei documenti
  * Tesi triennale: /Il problema dei due corpi e applicazioni astrofisiche/
    ([[https://github.com/giordano/Tesi-triennale][repository Git]], [[https://github.com/giordano/Tesi-triennale/tarball/master][sorgente]]), [[https://github.com/downloads/giordano/Tesi-triennale/presentazione.pdf][presentazione]] della tesi
  * Breve seminario sull'/energia oscura/ ([[https://github.com/downloads/giordano/seminario/seminario.pdf][presentazione]], [[https://github.com/giordano/seminario][repository Git]],
    [[https://github.com/giordano/seminario/tarball/master][sorgente]])
  * Seminario su progressi recenti (6 maggio 2013) nello studio dei raggi
    cosmici ([[file:allow_listing/raggi_cosmici.pdf][presentazione]], [[https://github.com/giordano/seminario-raggi-cosmici][repository Git]], [[https://github.com/giordano/seminario-raggi-cosmici/tarball/master][sorgente]]).  In particolare, sono
    presentati i risultati degli esperimenti FERMI-LAT (sulle sorgenti delle
    particelle accelerate) e AMS-02 (sull'eccesso della frazione di positroni
    nei raggi cosmici).
  * [[file:allow_listing/integrali_parametri.pdf][/Calcolo di integrali deﬁniti utilizzando integrali dipendenti da parametri/]]
    ([[file:allow_listing/integrali_parametri.tar.bz2][sorgente]])
  * [[file:allow_listing/diffusione.pdf][/Introduzione alla teoria della diffusione in meccanica quantistica/]]
    ([[https://github.com/giordano/diffusione-mq][repository Git]], [[https://github.com/giordano/diffusione-mq/archive/master.tar.gz][sorgente]]).  Appunti delle lezioni di Fisica teorica sullo
    scattering in meccanica quantistica.  Argomenti: forma asintotica degli
    stati stazionari, sezione d'urto, sviluppo in onde parziali e sfasamenti,
    equazione integrale della diffusione, serie di Born e approssimazione di
    Born, equazione di Lippmann-Schwinger
  * [[./allow_listing/gravitazione.pdf][/Gravitazione e cosmologia/]] ([[https://github.com/giordano/gravitazione][repository Git]], [[https://github.com/giordano/gravitazione/tarball/master][sorgente]]).  Dispense del corso
    su relatività generale e cosmologia tenuto all’Università del Salento dal
    professor Gabriele Ingrosso (avvertenza: /non ancora complete, potrebbero
    contenere alcune inesattezze/).  Argomenti: richiami di relatività speciale,
    trasformazioni di Lorentz, calcolo tensoriale nello spazio di Minkowski,
    dinamica particellare, formulazione covariante dell'elettrodinamica,
    equazioni di Eulero-Lagrange di un campo e tensore energia-impulso, fluido
    perfetto relativistico; principio di equivalenza, equazione del moto di una
    particella in un campo gravitazionale, tensore metrico e connessione affine,
    limite newtoniano, campo gravitomagnetico, effetto Lense-Thirring,
    dilatazione gravitazionale del tempo e red-shift, principio di generale
    covarianza; calcolo tensoriale nella relatività generale, tensori,
    connessione affine, derivazione covariante, differenziale covariante,
    effetto De Sitter; tensore di Riemann, curvatura dello spazio, equazione di
    deviazione geodetica, equazioni di Einstein e limite newtoniano, metrica di
    Schwarzschild, verifiche sperimentali della relatività generale (precessione
    del perielio, deflessione della luce, ritardo dei segnali radar); onde
    gravitazionali nel vuoto e in presenza di masse in moto, tecniche di
    rivelazione e sorgenti delle onde gravitazionali
  * [[./allow_listing/wiener.pdf][/Introduction to Wiener Filtering/]] ([[https://github.com/giordano/wiener-filter][Git repository]], [[https://github.com/giordano/wiener-filter/tarball/master][source]]).  Short
    presentation about Wiener Filtering to process images and signals in
    general.
- Altro (non sono opere mie originali)
  * [[file:allow_listing/intro_fisica_moderna.pdf][Dispense]] del corso di /Introduzione alla Fisica Moderna/ (corso di laurea
    triennale in Fisica), anno accademico 2008-2009 ([[file:allow_listing/intro_fisica_moderna.tar.xz][sorgente]]).  Argomenti:
    principio di d'Alembert ed equazioni di Lagrange, principio variazionale di
    Hamilton ed equazioni di Lagrange, applicazioni delle equazioni di Lagrange,
    Formalismo hamiltoniano, relatività speciale, introduzione alla meccanica
    quantistica.  Queste dispense sono una trascrizione dei lucidi utilizzati a
    lezione dal professore responsabile del corso.  Io ho solo sistemato un poco
    la versione digitale delle dispense ma non ne sono l'autore
  * [[file:allow_listing/prove_fisica.pdf][Prove d'esame]] ([[file:allow_listing/prove_fisica.tex][sorgente]]) di /Fisica III/ e /Fisica IV/ (corso di laurea
    triennale in Fisica)
  * [[file:allow_listing/prove_statistica.pdf][Prove d'esame]] ([[file:allow_listing/prove_statistica.tex][sorgente]]) di /Statistica e analisi numerica/ (corso di laurea
    triennale in Fisica), con soluzioni svolte da me di alcuni esercizi

*Posters*
- [[http://www.dmf.unisalento.it/~giordano/allow_listing/summer-course-exoplanets-2014-poster.pdf][Poster]] for the [[http://www.nordicastrobiology.net/Exoplanets2014/General.html][Summer Course on Exoplanets (2014)]], held at [[https://it.wikipedia.org/wiki/La_Palma][La Palma]] (Canary
  Islands, Spain) and presentation [[http://www.dmf.unisalento.it/~giordano/allow_listing/summer-course-exoplanets-2014-presentation.tar.gz][slides]]

$\LaTeX$
- Pacchetto [[file:allow_listing/particlessymb.sty][~particlessymb.sty~]] ([[https://github.com/giordano/particlessymb.sty][repository Git]]) per la composizione dei simboli
  delle particelle fisiche.  È basato su [[http://xml.web.cern.ch/XML/pennames/heppennames2.sty][~heppennames2.sty~]] e segue la sua
  stessa [[http://xml.web.cern.ch/XML/pennames/heppennames2.pdf][notazione]].  Fai clic [[file:particlessymb.org][qui]] per avere maggiori dettagli
- [[http://www.guitex.org/home/images/doc/GuideGuIT/guidamake.pdf][/Introduzione ai Makefile per compilare documenti LaTeX/]] ([[https://github.com/GuITeX/guidamakefilelatex][repository Git]],
  [[https://github.com/GuITeX/guidamakefilelatex/tarball/master][sorgente]]), pubblicata come [[http://www.guitex.org/home/it/guide-tematiche][guida tematica]] sul sito del [[http://www.guitex.org/home/][GuIT]] (Gruppo
  utilizzatori Italiani di TeX)
- [[http://www.guitex.org/home/images/doc/GuideGuIT/guidaemacsauctex.pdf][/Guida pratica all'uso di GNU Emacs e AUCTeX/]] ([[https://github.com/GuITeX/guidaemacsauctex][repository Git]], [[https://github.com/GuITeX/guidaemacsauctex/tarball/master][sorgente]]),
  pubblicata come [[http://www.guitex.org/home/it/guide-tematiche][guida tematica]] sul sito del [[http://www.guitex.org/home/][GuIT]] (Gruppo utilizzatori Italiani
  di TeX).  Scritta in collaborazione con Orlando Iovino e Matteo Leccardi
- [[http://www.guitex.org/home/images/doc/GuideGuIT/guidagit.pdf][/Una guida introduttiva a Git per progetti LaTeX/]] ([[https://github.com/GuITeX/guidagit][repository Git]], [[https://github.com/GuITeX/guidagit/tarball/master][sorgente]]),
  pubblicata come [[http://www.guitex.org/home/it/guide-tematiche][guida tematica]] sul sito del [[http://www.guitex.org/home/][GuIT]] (Gruppo utilizzatori Italiani
  di TeX).  Scritta in collaborazione con Pietro Giuffrida

*Fortran*
- [[file:fortran-debug.org][Debugging ~Fortran~ programs with GDB]] (in Italian)

*Emacs*
- [[file:allow_listing/emacs-pdt.pdf][/GNU Emacs powerful developing tool/]] (by Fabio Viola, in Italian): overview of
  some of the most famous developing tool for GNU Emacs
- I am one of the developers and co-maintainers of [[https://github.com/giordano/auctex-styles][AUCTeX]], a powerful Emacs
  package
- [[https://github.com/giordano/dotemacs][My init files]] for [[https://www.gnu.org/software/emacs/][Emacs]] (disclaimer: they are a bit messy)
- [[file:emacs-diceware.org][Emacs Lisp implementation of Diceware]] (in English)
- I contributed to [[https://mkmcc.github.io/software/bibslurp.html][~bibslurp.el~]], an Emacs package to retrieve BibTeX entries
  from [[http://adswww.harvard.edu/][NASA ADS]].

*Julia*

[[http://julialang.org/][Julia]] is a modern programming language, focussed on high-performance and
particularly useful for technical and scientific computing.  I am the author of
the following Julia packages:
- [[https://github.com/JuliaAstro/AstroLib.jl][~AstroLib.jl~]], a bundle of small astronomical and astrophysical routines.  It
  is based on famous IDL AstroLib.  You can read a short description [[file:astrolib-julia.org][here]]
- [[https://github.com/giordano/Cuba.jl][~Cuba.jl~]], a library for multidimensional numerical integration.  This is just
  a Julia wrapper around [[http://www.feynarts.de/cuba/][Cuba library]], by Thomas Hahn.  Complete documentation
  of =Cuba.jl= is available at http://cubajl.readthedocs.org/, also in [[https://media.readthedocs.org/pdf/cubajl/latest/cubajl.pdf][PDF
  format]].  You can read a short summary of features of the package and examples
  of use [[file:cuba-julia.org][here]]
- [[https://github.com/giordano/PolynomialRoots.jl][~PolynomialRoots.jl~]], a fast complex polynomial root finder, with support for
  arbitrary precision calculations.  [[file:polynomialroots-julia.org][Here]] is a brief description of the package
- [[https://github.com/giordano/Measurements.jl][~Measurements.jl~]], uncertainty propagation library.  Have a look at a short
  description [[file:measurements-julia.org][here]]
- [[https://github.com/giordano/LombScargle.jl][~LombScargle.jl~]], a package to perform the Lomb--Scargle periodogram, useful
  for unevenly sampled data.  Check out its [[file:lombscargle-julia.org][description]]
- [[https://github.com/JuliaDSP/Deconvolution.jl][~Deconvolution.jl~]], a package for deconvolution of digital signals.  Read this
  short [[file:deconvolution.org][description]] for more information

*Other softwares*
- I am one of the developers of [[https://gnu.org/software/gnuastro/][Gnuastro]], a package consisting of utilities for
  the manipulation and analysis of astronomical data

*ORCID*
- You can find my ORCID profile at https://orcid.org/0000-0002-7218-2873

*Public outreach*
- I collaborate for scientific news with Tom's Hardware Italia, top Italian
  online publication about technology and science.  Here is the list of the news
  I edited (in Italian): http://www.tomshw.it/utenti/list/mose-giordano-11662.
  Some of them have been syndicated to http://www.repubblica.it/, top Italian
  news website.
