#+TITLE: Mosè Giordano
#+LINK_HOME:

*Fisica e matematica*
- Miei documenti
  * Tesi triennale: /Il problema dei due corpi e applicazioni astrofisiche/
    ([[https://github.com/giordano/Tesi-triennale][repository Git]], [[https://github.com/giordano/Tesi-triennale/tarball/master][sorgente]]), [[https://github.com/downloads/giordano/Tesi-triennale/presentazione.pdf][presentazione]] della tesi
  * Breve seminario sull'/energia oscura/ ([[https://github.com/downloads/giordano/seminario/seminario.pdf][presentazione]], [[https://github.com/giordano/seminario][repository Git]],
    [[https://github.com/giordano/seminario/tarball/master][sorgente]])
  * [[file:allow_listing/integrali_parametri.pdf][/Calcolo di integrali deﬁniti utilizzando integrali dipendenti da parametri/]]
    ([[file:allow_listing/integrali_parametri.tar.bz2][sorgente]])
  * [[file:allow_listing/diffusione.pdf][/Introduzione alla teoria della diffusione in meccanica quantistica/]]
    ([[https://github.com/giordano/diffusione-mq][repository Git]], [[https://github.com/giordano/diffusione-mq/archive/master.tar.gz][sorgente]]).  Appunti delle lezioni di Fisica teorica sullo
    scattering in meccanica quantistica.  Argomenti: forma asintotica degli
    stati stazionari, sezione d'urto, sviluppo in onde parziali e sfasamenti,
    equazione integrale della diffusione, serie di Born e approssimazione di
    Born, equazione di Lippmann-Schwinger
  * [[./allow_listing/gravitazione.pdf][/Gravitazione e cosmologia/]] ([[https://github.com/giordano/gravitazione][repository Git]], [[https://github.com/giordano/gravitazione/tarball/master][sorgente]]).  Dispense (/non
    ancora complete né necessariamente corrette/) del corso di Gravitazione e
    cosmologia.  Argomenti: richiami di relatività speciale, trasformazioni di
    Lorentz, calcolo tensoriale nello spazio di Minkowski, dinamica
    particellare, formulazione covariante dell'elettrodinamica, equazioni di
    Eulero-Lagrange di un campo e tensore energia-impulso, fluido perfetto
    relativistico; principio di equivalenza, equazione del moto di una
    particella in un campo gravitazionale, tensore metrico e connessione affine,
    limite newtoniano, campo gravitomagnetico, effetto Lense-Thirring,
    dilatazione gravitazionale del tempo e red-shift, principio di generale
    covarianza; calcolo tensoriale nella relatività generale, tensori,
    connessione affine, derivazione covariante, differenziale covariante,
    effetto De Sitter; tensore di Riemann, curvatura dello spazio, equazione di
    deviazione geodetica, equazioni di Einstein e limite newtoniano, metrica di
    Schwarzschild, verifiche sperimentali della relatività generale (precessione
    del perielio, deflessione della luce, ritardo dei segnali radar); onde
    gravitazionali nel vuoto e in presenza di masse in moto, tecniche di
    rivelazione e sorgenti delle onde gravitazionali.
- Altro (non sono opere mie originali)
  * [[file:allow_listing/intro_fisica_moderna.pdf][Dispense]] del corso di /Introduzione alla Fisica Moderna/ (corso di laurea
    triennale in Fisica), anno accademico 2008-2009 ([[file:allow_listing/intro_fisica_moderna.tar.xz][sorgente]]).  Argomenti:
    principio di d'Alembert ed equazioni di Lagrange, principio variazionale di
    Hamilton ed equazioni di Lagrange, applicazioni delle equazioni di Lagrange,
    Formalismo hamiltoniano, relatività speciale, introduzione alla meccanica
    quantistica.  Queste dispense sono una trascrizione dei lucidi utilizzati a
    lezione dal professore responsabile del corso.  Io ho solo sistemato un poco
    la versione digitale delle dispense ma non ne sono l'autore.
  * [[file:allow_listing/prove_fisica.pdf][Prove d'esame]] ([[file:allow_listing/prove_fisica.tex][sorgente]]) di /Fisica III/ e /Fisica IV/ (corso di laurea
    triennale in Fisica)
  * [[file:allow_listing/prove_statistica.pdf][Prove d'esame]] ([[file:allow_listing/prove_statistica.tex][sorgente]]) di /Statistica e analisi numerica/ (corso di laurea
    triennale in Fisica), con soluzioni svolte da me di alcuni esercizi

$\LaTeX$
- Pacchetto [[file:allow_listing/particlessymb.sty][~particlessymb.sty~]] ([[https://github.com/giordano/particlessymb.sty][repository Git]]) per la composizione dei simboli
  delle particelle fisiche.  È basato su [[http://xml.web.cern.ch/XML/pennames/heppennames2.sty][~heppennames2.sty~]] e segue la sua
  stessa [[http://xml.web.cern.ch/XML/pennames/heppennames2.pdf][notazione]].  Fai clic [[file:particlessymb.org][qui]] per avere maggiori dettagli
- [[http://www.guitex.org/home/images/doc/GuideGuIT/guidamake.pdf][/Introduzione ai Makefile per compilare documenti LaTeX/]] ([[https://github.com/GuITeX/guidamakefilelatex][repository Git]],
  [[https://github.com/GuITeX/guidamakefilelatex/tarball/master][sorgente]]), pubblicata come [[http://www.guitex.org/home/it/guide-tematiche][guida tematica]] sul sito del [[http://www.guitex.org/home/][GuIT]] (Gruppo
  utilizzatori Italiani di TeX)

*Misc*
- [[file:allow_listing/emacs-pdt.pdf][/GNU Emacs powerful developing tool/]] (di Fabio Viola): panoramica di alcuni
  dei più famosi strumenti per lo sviluppo presenti in GNU Emacs
