;; aggiungi al file di inizializzazione ~/.emacs questo codice
;; 	(load-file "~/repo/sito/sito")
;; per caricare automaticamente questo file.  In questo modo puoi pubblicare il
;; sito semplicemente con `C-c C-e P' dentro un buffer dei file *.org del
;; progetto.

;; For detection of author and date see `org-html-format-spec' function.
(defun my-website-postamble (info)
  (concat "\
<div style=\"font-size: smaller; background: #f2f2f9; border: 2px solid #3366cc;
            border-style: solid; border-width: thin; padding: 4px;\">
<p class=\"author\">Author: " (org-export-data (plist-get info :author) info)
"</p>
<p class=\"date\">Last modified: "
(let ((file (plist-get info :input-file)))
  (format-time-string org-html-metadata-timestamp-format
		      (if file (nth 5 (file-attributes file))
			(current-time)))) "</p>
<p class=\"creator\">Generated by <a href=\"http://orgmode.org/\">Org mode</a> \
version " org-version " with <a href=\"http://www.gnu.org/software/emacs/\">GNU \
Emacs</a> version " emacs-version ".  \
The <a href=\"https://github.com/giordano/sito\">source code</a> of the web-site \
is available on Github</p>
<p class=\"license\"><a rel=\"license\" \
href=\"http://creativecommons.org/licenses/by/3.0/it/\">\
<img alt=\"Licenza Creative Commons\" style=\"border-width:0\" \
src=\"http://i.creativecommons.org/l/by/3.0/it/80x15.png\" /></a> This site \
is licensed under terms of <a rel=\"license\" \
href=\"https://creativecommons.org/licenses/by/3.0/\">Creative \
Commons Attribution 3.0</a></p>
<p class=\"xhtml-validation\">
<a href=\"http://validator.w3.org/check?uri=referer\">XHTML 1.0 Validator</a>
</p></div>\n"))

(setq org-publish-project-alist
      '(
	("sito-content"
	 :base-directory "~/repo/sito"
	 :base-extension "org"
	 :publishing-directory "/ssh:infn:html/"
	 :publishing-function org-html-publish-to-html
	 :author "Mosè Giordano"
	 :language "it"
	 :html-link-home "index.html"
	 :with-smart-quotes nil)
	("sito" :components ("sito-content")))
      org-html-postamble 'my-website-postamble)
